# definir el alcance de los hosts
- name: Deployment de un sitio estatico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el OS es Ubuntu
      set_fact:
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  vars_files:
    - vars/vars-site.yml
  tasks:
    - name: Instalar servicio Apache
      include_tasks: includes/apache/install-apache2.yml

    - name: Crear directorio para el sitio
      include_tasks: includes/site-estatic/create-directory.yml

    - name: Copiar index.html al directorio del sitio
      include_tasks: includes/site-estatic/copy-index.yml

    - name: Configuracion del sitio apache
      include_tasks: includes/apache/config-apache2.yml

    - name: Activa el nuevo sitio
      include_tasks: includes/site-estatic/activation-site.yml

    - name: Deshabilita el sitio default
      include_tasks: includes/site-estatic/desable-default-site.yml

    - name: Cambiar el e-mail del webmaster
      include_tasks: includes/site-estatic/change-email.yml
      
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
      when: is_ubuntu